name    'ruckc-powershell'
version '0.0.3'
source 'git://github.com/ruckc/puppetlabs-powershell.git'
author 'Curtis Ruck'
license 'Apache License, Version 2.0'
summary 'A PowerShell provider for puppet.'
description 'A PowerShell provider for puppet with 32 and 64 bit powershell providers'
project_page 'http://links.puppetlabs.com/powershell-module'
